# Generated by Django 2.2 on 2020-07-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_catagory', models.CharField(choices=[('python', 'python'), ('java', 'java'), ('php', 'php')], default='', max_length=100)),
                ('book_name', models.CharField(max_length=100)),
                ('book_price', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_desc', models.TextField()),
                ('book_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
